%YAML 1.2
---
drawings:
  EL-000-01:
    discipline: ELECTRICAL
    scale: NTS
    title: LEGEND
    type: legend
  EL-100-01:
    discipline: ELECTRICAL
    scale: 1:500
    title: SITE PLAN
    type: layout
  EL-200-01:
    discipline: ELECTRICAL
    scale: 1:100
    title: LIGHTING & FIRE DETECTION LAYOUT
    type: layout
  EL-300-01:
    discipline: ELECTRICAL
    scale: 1:100
    title: POWER & COMMUNICATIONS LAYOUT
    type: layout
  EL-800-01:
    discipline: ELECTRICAL
    scale: NTS
    title: DETAILS
    type: details
  EL-900-01:
    discipline: ELECTRICAL
    scale: NTS
    title: SINGLE LINE DIAGRAMS
    type: SLD
meta:
  approved by: KH
  client: INTERNAL
  construction status: NOT FOR CONSTRUCTION
  drawn by: PUNE
  issue date: '2022-12-25'
  issue description: ISSUED FOR INFORMATION
  project name: PROJECT
  project number: '301299999'
  rev: A
  stamp: PRELIMINARY
  status: ABC
